export class User {
    id?:any;
	uniqueId?:any;
	description?:any;
	username?:any;
	firstname?:any;
	lastname?:any;
	email?:any;
	password?:any;
	profile?:any;
	profileUrl?:any;
	phone?:any;
	country?:any;
	city?:any;
	address?:any;
	dateCreation?:any;
	dateModification?:any;
	status?:any;
	code?:any;
	codeExpiryDate?:any;
	isBanned?:any;
	bannedAt?:any;
	profession?:any;
	isOnline?:any;
	lastIp?:any;
	lastConnectionTime?:any;
    role?: any;
    roles?: any;
    token?: any;
}